version: "2"

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/src
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    #image: php:7-fpm
    volumes:
      - ./src:/src
      - ./log.conf:/var/logs/php-fpm.d/zz-log.conf
    networks:
      - code-network

  composer:
    image: composer:latest
    networks:
      - code-network

  db:
    image: mysql:latest
    volumes:
      - /var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: myapp
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
